package com.nitrous.gwt.earth.client.api.event;

import com.nitrous.gwt.earth.client.api.KmlEvent;

/**
 * The generic event listener that can be registered by calling <code>GoogleEarth.addEventListener</code>
 * @author Nick
 *
 */
public interface KmlEventListener {
    /**
     * Called when an event is generated by google earth matching the registered event ID. 
     * @param event The KmlEvent that was generated by Google Earth
     */
    void onEvent(KmlEvent event);
}
