/*
 * Copyright 2012 Nick Kerr
 *
 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package com.nitrous.gwt.earth.client.api.event;

import com.nitrous.gwt.earth.client.api.KmlEvent;

/**
 * The generic event listener that can be registered by calling <code>GoogleEarth.addEventListener</code>
 * @author Nick
 *
 */
public interface KmlEventListener {
    /**
     * Called when an event is generated by google earth matching the registered event ID. 
     * @param event The KmlEvent that was generated by Google Earth
     */
    void onEvent(KmlEvent event);
}
